Repository bigbluebutton/bigbluebutton, pull requests merged in 2021-08, with the labels that each got.

#12866 Update Manage Users Dropdown To Menu
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
Labels: target: accessibilty

#12921 chore: Pulled HTML5 locales - Aug 5, 2021
  bigbluebutton-html5/public/locales/ar.json
  bigbluebutton-html5/public/locales/de.json
  bigbluebutton-html5/public/locales/eu.json
  bigbluebutton-html5/public/locales/fr.json
  bigbluebutton-html5/public/locales/gl.json
  bigbluebutton-html5/public/locales/it_IT.json
  bigbluebutton-html5/public/locales/ja.json
  bigbluebutton-html5/public/locales/lt_LT.json
  bigbluebutton-html5/public/locales/nl.json
  bigbluebutton-html5/public/locales/ru.json
  bigbluebutton-html5/public/locales/tr_TR.json
  bigbluebutton-html5/public/locales/zh_TW.json
Labels: target: localization

#12536 consider bbb-webrtc-sfu and bbb-html5 overrides
  bigbluebutton-config/bin/bbb-conf
Labels: cla: signed

#12976 chore: Pulled HTML5 locales on Aug 11, 2021
  bigbluebutton-html5/public/locales/bn.json
  bigbluebutton-html5/public/locales/de.json
Labels: target: localization

#12984 chore: Pulled partial locales 2.4 HTML5 on Aug 11, 2021
  bigbluebutton-html5/public/locales/ar.json
  bigbluebutton-html5/public/locales/de.json
  bigbluebutton-html5/public/locales/et.json
  bigbluebutton-html5/public/locales/fa_IR.json
  bigbluebutton-html5/public/locales/gl.json
  bigbluebutton-html5/public/locales/id.json
  bigbluebutton-html5/public/locales/it_IT.json
  bigbluebutton-html5/public/locales/ja.json
  bigbluebutton-html5/public/locales/lt_LT.json
  bigbluebutton-html5/public/locales/lv.json
  bigbluebutton-html5/public/locales/tr_TR.json
  bigbluebutton-html5/public/locales/uk_UA.json
  bigbluebutton-html5/public/locales/zh_TW.json
Labels: target: localization

#13029 Avoid race condition between redis and bbb-rap-resque-worker
  record-and-playback/core/systemd/bbb-rap-resque-worker.service
Labels: module: recording

#13110 packaging: renamed bbb-activity-report to bbb-learning-dashboard
  .gitlab-ci.yml
  build/package-names.inc.sh
  build/packages-template/bbb-activity-report/after-remove.sh
  build/packages-template/bbb-learning-dashboard/after-install.sh
  build/packages-template/bbb-learning-dashboard/after-remove.sh
  build/packages-template/bbb-learning-dashboard/before-install.sh
  build/packages-template/bbb-learning-dashboard/build.sh
  build/packages-template/bbb-learning-dashboard/opts-bionic.sh
  build/packages-template/bigbluebutton/build.sh
Labels: deploy: packaging

#13120 chore: Pulled HTML5 locales on Aug 31, 2021
  bigbluebutton-html5/public/locales/id.json
  bigbluebutton-html5/public/locales/oc.json
  bigbluebutton-html5/public/locales/zh_TW.json
Labels: target: localization
