Repository bigbluebutton/bigbluebutton, pull requests merged in 2021-04, with the labels that each got.

#11831 Improvements in muted banner
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
  bigbluebutton-html5/imports/ui/components/muted-alert/component.jsx
Labels: HTML5 Client, audio

#11841 Change browser detection library to bowser
  bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
  bigbluebutton-html5/imports/startup/client/base.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/component.jsx
  bigbluebutton-html5/imports/ui/components/app/component.jsx
  bigbluebutton-html5/imports/ui/components/app/container.jsx
  bigbluebutton-html5/imports/ui/components/app/service.js
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
  bigbluebutton-html5/imports/ui/components/audio/device-selector/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/component.jsx
  bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/legacy/component.jsx
  bigbluebutton-html5/imports/ui/components/media/component.jsx
  bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
  bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/theteredDropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
  bigbluebutton-html5/imports/ui/components/video-provider/service.js
  bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
  bigbluebutton-html5/imports/utils/browserInfo.js
  bigbluebutton-html5/imports/utils/deviceInfo.js
  bigbluebutton-html5/package-lock.json
  bigbluebutton-html5/package.json
Labels: HTML5 Client

#11848 Merged 2.2.36 into 2.3-beta
  bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
  bigbluebutton-html5/imports/api/captions/server/helpers.js
  bigbluebutton-html5/imports/api/captions/server/methods/appendText.js
  bigbluebutton-html5/imports/api/captions/server/methods/createCaptions.js
  bigbluebutton-html5/imports/api/captions/server/methods/fetchReadOnlyPadId.js
  bigbluebutton-html5/imports/api/common/server/etherpad.js
  bigbluebutton-html5/imports/api/common/server/helpers.js
  bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
  bigbluebutton-html5/imports/api/note/server/helpers.js
  bigbluebutton-html5/imports/api/note/server/methods/createNote.js
  bigbluebutton-html5/imports/ui/components/captions/service.js
Labels: HTML5 Client

#11849 fix: MEDIA_ERROR when joining room using Firefox
  bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
  bigbluebutton-html5/imports/ui/components/audio/container.jsx
  bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Labels: audio

#11853 Pulled HTML5 locales on Apr 1, 2021
  bigbluebutton-html5/public/locales/ar.json
  bigbluebutton-html5/public/locales/az.json
  bigbluebutton-html5/public/locales/bg_BG.json
  bigbluebutton-html5/public/locales/ca.json
  bigbluebutton-html5/public/locales/cs_CZ.json
  bigbluebutton-html5/public/locales/da.json
  bigbluebutton-html5/public/locales/de.json
  bigbluebutton-html5/public/locales/el_GR.json
  bigbluebutton-html5/public/locales/eo.json
  bigbluebutton-html5/public/locales/es.json
  bigbluebutton-html5/public/locales/es_ES.json
  bigbluebutton-html5/public/locales/et.json
  bigbluebutton-html5/public/locales/fa_IR.json
  bigbluebutton-html5/public/locales/fr.json
  bigbluebutton-html5/public/locales/gl.json
  bigbluebutton-html5/public/locales/he.json
  bigbluebutton-html5/public/locales/hu_HU.json
  bigbluebutton-html5/public/locales/it_IT.json
  bigbluebutton-html5/public/locales/ja.json
  bigbluebutton-html5/public/locales/ko_KR.json
  bigbluebutton-html5/public/locales/lt_LT.json
  bigbluebutton-html5/public/locales/nl.json
  bigbluebutton-html5/public/locales/oc.json
  bigbluebutton-html5/public/locales/pt.json
  bigbluebutton-html5/public/locales/ru.json
  bigbluebutton-html5/public/locales/ru_RU.json
  bigbluebutton-html5/public/locales/sk_SK.json
  bigbluebutton-html5/public/locales/sl.json
  bigbluebutton-html5/public/locales/sr.json
  bigbluebutton-html5/public/locales/te.json
  bigbluebutton-html5/public/locales/tr.json
  bigbluebutton-html5/public/locales/tr_TR.json
  bigbluebutton-html5/public/locales/uk_UA.json
  bigbluebutton-html5/public/locales/zh_CN.json
  bigbluebutton-html5/public/locales/zh_TW.json
Labels: HTML5 Client, Localization

#11854 Set breakoutRoomLimit to 16
  bigbluebutton-html5/private/config/settings.yml
Labels: HTML5 Client, breakouts

#11880 Set new labels to templates and workflows
  .github/ISSUE_TEMPLATE/core-issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/html5-issue.md
  .github/ISSUE_TEMPLATE/installation-issue.md
  .github/ISSUE_TEMPLATE/recording-issue.md
  .github/workflows/check-merge-conflict.yml
Labels: target: maintainability, type: enhancement

#11885 Changes showAllAvailableLocales settings default value
  bigbluebutton-html5/private/config/settings.yml
Labels: module: client

#11886 Fix settings modal z-index
  bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
Labels: module: client

#11847 Re-include offline users to the connection modal's users list
  bigbluebutton-html5/imports/api/users-persistent-data/server/publishers.js
  bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
  bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.scss
  bigbluebutton-html5/imports/ui/components/connection-status/service.js
  bigbluebutton-html5/public/locales/en.json
Labels: module: client

#11884 Services run as starting PID
  akka-bbb-apps/run-dev.sh
  akka-bbb-apps/run.sh
  akka-bbb-fsesl/run-dev.sh
  akka-bbb-fsesl/run.sh
  bbb-lti/docker-entrypoint.sh
  bbb-lti/run.sh
  bigbluebutton-html5/docker-entrypoint.sh
  bigbluebutton-web/docker-entrypoint.sh
  bigbluebutton-web/pres-checker/run.sh
  bigbluebutton-web/run-prod.sh
  bigbluebutton-web/run.sh
Labels: cla: signed, deploy: configuration

#11889 Offline users' connection status improvements
  bigbluebutton-html5/imports/ui/components/connection-status/service.js
Labels: module: client

#11824 Fix unread message indicator remaining visible
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx
Labels: component: chat, module: client

#11890 Fix unread notes being not shown in navbar
  bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
Labels: module: client

#11826 Add connection status (++ webcams, screenshare) test specs
  bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx
  bigbluebutton-html5/tests/puppeteer/core/elements.js
  bigbluebutton-html5/tests/puppeteer/core/page.js
  bigbluebutton-html5/tests/puppeteer/core/profiles.js
  bigbluebutton-html5/tests/puppeteer/screenshare/util.js
  bigbluebutton-html5/tests/puppeteer/user.obj.js
  bigbluebutton-html5/tests/puppeteer/user/elements.js
  bigbluebutton-html5/tests/puppeteer/user/status.js
  bigbluebutton-html5/tests/puppeteer/user/util.js
Labels: type: test

#11904 fix: audio device selector problem when using RTL locales
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/styles.scss
Labels: module: client

#11907 Fix action button appearing over userlist and dropdown
  bigbluebutton-html5/imports/ui/components/app/styles.scss
Labels: module: client

#11910 Adding new function to clear all status
  bigbluebutton-html5/imports/ui/components/user-list/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/container.jsx
  bigbluebutton-html5/imports/ui/components/user-list/service.js
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx
Labels: module: client

#11912 fix: dial-in users don't appear in participant's list
  bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/addUserPersistentData.js
Labels: module: client

#11900 Fire layout rearrangement by toggling poll panel
  bigbluebutton-html5/imports/ui/components/poll/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-polls/component.jsx
Labels: module: client

#11892 Localized quick poll answers
  bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
Labels: component: polling, module: client

#11922 Fix Keyboard Navigation Skipping Users In Userlist
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
Labels: module: client

#11928 Do not show real font-size in whiteboard text tool button
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu/component.jsx
Labels: module: client

#11925 Trigger layout rearrangement by quick poll button
  bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
Labels: module: client

#11920 Fix user icons alignment for Microsoft Edge browser
  bigbluebutton-html5/imports/ui/stylesheets/mixins/_indicators.scss
  bigbluebutton-html5/imports/ui/stylesheets/variables/general.scss
Labels: module: client

#11932 Remove old Edge specific code
  bigbluebutton-html5/imports/ui/components/audio/permissions-overlay/styles.scss
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
  bigbluebutton-html5/imports/ui/stylesheets/mixins/_scrollable.scss
Labels: module: client

#11948 Makes presenter menu scrollable
  bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
Labels: module: client

#11940 Remove recording button text on phones
  bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/container.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss
Labels: module: client

#11945 Fix Text Area's Not Opening IOS Virtual Keyboard
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx
Labels: module: client

#11911 Fix client crashing because users object is missing
  bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/container.jsx
  bigbluebutton-html5/imports/ui/components/components-data/users-context/context.jsx
  bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
  bigbluebutton-html5/imports/ui/components/presentation/container.jsx
  bigbluebutton-html5/imports/ui/components/status-notifier/container.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/container.jsx
  bigbluebutton-html5/imports/ui/components/waiting-users/alert/container.jsx
Labels: module: client

#11950 fix: when muted alert is active, can't click on 'Leave audio'
  bigbluebutton-html5/imports/ui/components/muted-alert/styles.scss
Labels: module: client

#11953 Remove unused chat-related variables
  bigbluebutton-html5/imports/ui/components/chat/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/service.js
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx
  bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx
Labels: module: client

#11951 Fix new poll key warning
  bigbluebutton-html5/imports/ui/components/poll/component.jsx
Labels: module: client

#11927 Update order of presentation lists
  bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Labels: module: client

#11963 Formatting of PIN number within client
  bigbluebutton-html5/imports/ui/components/audio/audio-dial/component.jsx
Labels: module: client

#11906 Prevent users from sending private messages to offline user
  bigbluebutton-html5/imports/ui/components/chat/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Labels: module: client

#11967 Update eslint to ecma 2020
  bigbluebutton-html5/.eslintrc.js
  bigbluebutton-html5/package-lock.json
  bigbluebutton-html5/package.json
Labels: module: client

#11956 Creates a pubSub error message when Upload max size exceeded
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPodHdlrs.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationUploadTokenReqMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationUploadedFileTooLargeErrorPubMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala
  bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/PresentationPodsMsgs.scala
  bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/PresentationUploadToken.java
  bbb-common-web/src/main/java/org/bigbluebutton/presentation/ConversionMessageConstants.java
  bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SwfSlidesGenerationProgressNotifier.java
  bbb-common-web/src/main/java/org/bigbluebutton/presentation/messages/UploadFileTooLargeMessage.java
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
  bigbluebutton-web/bbb-web.nginx
  bigbluebutton-web/grails-app/conf/spring/resources.xml
  bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
Labels: component: presentation, module: core

#11994 Fix save and copy messages
  bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/service.js
Labels: component: chat, module: client

#11995 fix: whiteboard access for multiple presentations
  bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Labels: component: presentation, module: client

#11989 Fix private public chat lock interference
  bigbluebutton-html5/imports/ui/components/chat/container.jsx
Labels: module: client

#12000 Fix active poll refresh crash
  bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Labels: component: polling, module: client

#12002 Remove max-width from polling options container
  bigbluebutton-html5/imports/ui/components/polling/styles.scss
Labels: component: polling, module: client

#11997 Fix panel resizing for poll, cc and waiting list
  bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
Labels: module: client

#11992 Fix chat alerts
  bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/service.js
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/container.jsx
  bigbluebutton-html5/imports/ui/services/unread-messages/index.js
Labels: component: chat, module: client

#11957 Extend user's name sorting to use non-ASCII characters
  bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
  bigbluebutton-html5/imports/ui/components/breakout-room/service.js
  bigbluebutton-html5/imports/ui/components/user-list/service.js
Labels: module: client

#12015 Scroll on polling panel - mobile
  bigbluebutton-html5/imports/ui/components/app/styles.scss
Labels: component: polling, module: client

#12012 Fix duplicated messages
  bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx
  bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx
  bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
Labels: component: chat, module: client

#12010 Fix previous messages chat alerts and remove unused code
  bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/service.js
Labels: component: chat, module: client

#12013 Fix: Allow open private chats with mods if private chats are disabled
  bigbluebutton-html5/imports/ui/components/chat/container.jsx
Labels: component: chat, module: client

#12037 Make audio selection menu scrollable
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
Labels: module: client

#11224 Fix unintetionally drawing while using an active pencil
  bigbluebutton-html5/client/stylesheets/bbb-icons.css
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/pencil-pointer-listener/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/shape-pointer-listener/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/container.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/service.js
  bigbluebutton-html5/public/fonts/BbbIcons/bbb-icons.woff
  bigbluebutton-html5/public/locales/de.json
  bigbluebutton-html5/public/locales/en.json
Labels: cla: signed, component: whiteboard, priority: high, type: enhancement

#12008 Export Shared Notes to PDF/DOC/ODT
  bbb-libreoffice/assets/convert-local.sh
  bbb-libreoffice/assets/convert-remote.sh
  bbb-libreoffice/assets/etherpad-export.sh
  bbb-libreoffice/assets/zzz-bbb-docker-libreoffice
  bbb-libreoffice/install-local.sh
  bbb-libreoffice/install-remote.sh
Labels: component: presentation, component: shared notes

#12045 Add bars to chat poll results
  bigbluebutton-html5/imports/api/polls/server/handlers/sendPollChatMsg.js
Labels: component: polling, module: client

#12011 Publish cursor using reliable userId
  bigbluebutton-html5/imports/api/cursor/server/handlers/cursorUpdate.js
  bigbluebutton-html5/imports/api/cursor/server/streamer.js
  bigbluebutton-html5/imports/ui/components/cursor/service.js
Labels: module: client

#12034 Add meetingId to usersContext
  bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/container.jsx
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx
  bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx
  bigbluebutton-html5/imports/ui/components/components-data/users-context/context.jsx
  bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
  bigbluebutton-html5/imports/ui/components/presentation/container.jsx
  bigbluebutton-html5/imports/ui/components/status-notifier/container.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/container.jsx
  bigbluebutton-html5/imports/ui/components/waiting-users/alert/container.jsx
Labels: module: client

#12003 Fix join webcam breakout room
  bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Labels: module: client

#12079 Fix regression: Unintentional locking of private chat with moderator, chat lock on left/ejected user not triggered
  bigbluebutton-html5/imports/ui/components/chat/container.jsx
Labels: component: chat, module: client

#12078 Make Breakout Rooms User Assignment Keyboard Accessible
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
Labels: module: client, target: accessibilty

#12081 Get users data from context in poll live-result
  bigbluebutton-html5/imports/ui/components/poll/component.jsx
  bigbluebutton-html5/imports/ui/components/poll/container.jsx
  bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
  bigbluebutton-html5/imports/ui/components/poll/live-result/service.js
Labels: module: client

#12082 Get users data from context in random user select
  bigbluebutton-html5/imports/ui/components/modal/random-user/container.jsx
Labels: module: client

#12077 Fix Screen Reader Access To Tethered Dropdown Menu's
  bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
Labels: module: client, target: accessibilty

#12095 Update Language On Html After Locale Change
  bigbluebutton-html5/imports/ui/components/settings/component.jsx
Labels: module: client, target: accessibilty

#12059 Fix layout doesn't update when screen is shared
  bigbluebutton-html5/imports/startup/client/base.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
  bigbluebutton-html5/imports/ui/components/app/component.jsx
  bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx
  bigbluebutton-html5/imports/ui/components/layout/layout-manager/container.jsx
  bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
  bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
Labels: component: layout, module: client

#12054 fix: mic selection (firefox/all browsers) and muted alert when mic is changed
  bigbluebutton-html5/.eslintrc.js
  bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
  bigbluebutton-html5/imports/ui/components/muted-alert/component.jsx
  bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Labels: module: audio, module: client

#12101 fix: breakout autojoin audio with wrong behavior
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/container.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
  bigbluebutton-html5/imports/ui/components/audio/audio-modal/service.js
  bigbluebutton-html5/imports/ui/components/audio/container.jsx
Labels: component: breakout rooms, module: audio, module: client

#12104 Fix Focus Outline Clipping Buttons In Firefox
  bigbluebutton-html5/imports/ui/components/button/styles.scss
Labels: module: client

#12109 Makes hand raised message differentiate between one and multiple users
  bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx
  bigbluebutton-html5/public/locales/en.json
Labels: module: client

#12116 Fix client crashing with multiple private chats
  bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx
Labels: component: chat, module: client

#11931 Stop viewer play/stop actions on external videos
  bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
Labels: module: client

#12134 Pulled HTML5 locales on Apr 23, 2021
  bigbluebutton-html5/public/locales/ar.json
  bigbluebutton-html5/public/locales/az.json
  bigbluebutton-html5/public/locales/ca.json
  bigbluebutton-html5/public/locales/cs_CZ.json
  bigbluebutton-html5/public/locales/da.json
  bigbluebutton-html5/public/locales/de.json
  bigbluebutton-html5/public/locales/el_GR.json
  bigbluebutton-html5/public/locales/eo.json
  bigbluebutton-html5/public/locales/es.json
  bigbluebutton-html5/public/locales/es_ES.json
  bigbluebutton-html5/public/locales/fa_IR.json
  bigbluebutton-html5/public/locales/fr.json
  bigbluebutton-html5/public/locales/gl.json
  bigbluebutton-html5/public/locales/hu_HU.json
  bigbluebutton-html5/public/locales/it_IT.json
  bigbluebutton-html5/public/locales/ja.json
  bigbluebutton-html5/public/locales/ko_KR.json
  bigbluebutton-html5/public/locales/lt_LT.json
  bigbluebutton-html5/public/locales/nl.json
  bigbluebutton-html5/public/locales/pt.json
  bigbluebutton-html5/public/locales/ru.json
  bigbluebutton-html5/public/locales/ru_RU.json
  bigbluebutton-html5/public/locales/sl.json
  bigbluebutton-html5/public/locales/sr.json
  bigbluebutton-html5/public/locales/sv_SE.json
  bigbluebutton-html5/public/locales/te.json
  bigbluebutton-html5/public/locales/tr.json
  bigbluebutton-html5/public/locales/tr_TR.json
  bigbluebutton-html5/public/locales/uk_UA.json
  bigbluebutton-html5/public/locales/zh_CN.json
  bigbluebutton-html5/public/locales/zh_TW.json
Labels: target: localization

#12124 Implements forceRasterizeSlides and pngWidthRasterizedSlides
  bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
  bigbluebutton-web/grails-app/conf/bigbluebutton.properties
  bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml
Labels: component: presentation

#12107 [add] enable bbb-webhooks to bind nodejs localhost, and make it default
  bbb-webhooks/application.js
  bbb-webhooks/config/custom-environment-variables.yml
  bbb-webhooks/config/default.example.yml
  bbb-webhooks/web_server.js
Labels: module: webhook

#12179 Make Screen Readers Auto Announce Chat Messages
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Labels: component: chat, target: accessibilty

#12177 fix: Fix Active Style For Current Chat
  bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/styles.scss
Labels: component: chat, target: accessibilty

#12192 refactor(screenshare): remove unused extension/support checks
  bigbluebutton-html5/imports/ui/components/media/container.jsx
  bigbluebutton-html5/public/locales/en.json
Labels: module: client

#12169 Make random user picking coundown (UI + audio) optional
  bigbluebutton-html5/imports/ui/components/modal/random-user/component.jsx
  bigbluebutton-html5/private/config/settings.yml
Labels: module: client

#12202 Cutoff poll responses
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToPollReqMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToTypedPollReqMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala
Labels: component: polling, module: core

#12212 Add configuration for max length typed answer in poll
  bigbluebutton-html5/imports/api/polls/server/methods/publishTypedVote.js
  bigbluebutton-html5/imports/ui/components/poll/component.jsx
  bigbluebutton-html5/imports/ui/components/polling/component.jsx
  bigbluebutton-html5/private/config/settings.yml
Labels: component: polling, module: client

#12100 Improve feedback to user after a failed file upload
  bigbluebutton-html5/imports/api/presentations/server/eventHandlers.js
  bigbluebutton-html5/imports/api/presentations/server/handlers/presentationConversionUpdate.js
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss
  bigbluebutton-html5/private/config/settings.yml
  bigbluebutton-html5/public/locales/en.json
Labels: component: presentation, module: client

#12208 Recording: Fix handling of recordings without recording marks
  bigbluebutton-config/bin/bbb-record
  record-and-playback/core/lib/recordandplayback/workers/archive_worker.rb
  record-and-playback/core/lib/recordandplayback/workers/base_worker.rb
  record-and-playback/core/lib/recordandplayback/workers/sanity_worker.rb
  record-and-playback/core/scripts/rap-enqueue.rb
Labels: module: recording

#12216 chore(locales): Pulled HTML5 locales; Added Afrikaans
  bigbluebutton-html5/public/locales/af.json
  bigbluebutton-html5/public/locales/ar.json
  bigbluebutton-html5/public/locales/az.json
  bigbluebutton-html5/public/locales/bg_BG.json
  bigbluebutton-html5/public/locales/ca.json
  bigbluebutton-html5/public/locales/cs_CZ.json
  bigbluebutton-html5/public/locales/da.json
  bigbluebutton-html5/public/locales/de.json
  bigbluebutton-html5/public/locales/el_GR.json
  bigbluebutton-html5/public/locales/eo.json
  bigbluebutton-html5/public/locales/es.json
  bigbluebutton-html5/public/locales/es_ES.json
  bigbluebutton-html5/public/locales/es_MX.json
  bigbluebutton-html5/public/locales/et.json
  bigbluebutton-html5/public/locales/eu.json
  bigbluebutton-html5/public/locales/fa_IR.json
  bigbluebutton-html5/public/locales/fi.json
  bigbluebutton-html5/public/locales/fr.json
  bigbluebutton-html5/public/locales/gl.json
  bigbluebutton-html5/public/locales/he.json
  bigbluebutton-html5/public/locales/hi_IN.json
  bigbluebutton-html5/public/locales/hr.json
  bigbluebutton-html5/public/locales/hu_HU.json
  bigbluebutton-html5/public/locales/id.json
  bigbluebutton-html5/public/locales/it_IT.json
  bigbluebutton-html5/public/locales/ja.json
  bigbluebutton-html5/public/locales/ka.json
  bigbluebutton-html5/public/locales/km.json
  bigbluebutton-html5/public/locales/kn.json
  bigbluebutton-html5/public/locales/ko_KR.json
  bigbluebutton-html5/public/locales/lt_LT.json
  bigbluebutton-html5/public/locales/lv.json
  bigbluebutton-html5/public/locales/nb_NO.json
  bigbluebutton-html5/public/locales/nl.json
  bigbluebutton-html5/public/locales/oc.json
  bigbluebutton-html5/public/locales/pl_PL.json
  bigbluebutton-html5/public/locales/pt.json
  bigbluebutton-html5/public/locales/pt_BR.json
  bigbluebutton-html5/public/locales/ro_RO.json
  bigbluebutton-html5/public/locales/ru.json
  bigbluebutton-html5/public/locales/ru_RU.json
  bigbluebutton-html5/public/locales/sk_SK.json
  bigbluebutton-html5/public/locales/sl.json
  bigbluebutton-html5/public/locales/sr.json
  bigbluebutton-html5/public/locales/sv_SE.json
  bigbluebutton-html5/public/locales/te.json
  bigbluebutton-html5/public/locales/th.json
  bigbluebutton-html5/public/locales/th_TH.json
  bigbluebutton-html5/public/locales/tr.json
  bigbluebutton-html5/public/locales/tr_TR.json
  bigbluebutton-html5/public/locales/uk_UA.json
  bigbluebutton-html5/public/locales/vi_VN.json
  bigbluebutton-html5/public/locales/zh_CN.json
  bigbluebutton-html5/public/locales/zh_TW.json
Labels: module: client, target: localization

#12213 feature(bbb-html5): localize guest-wait.html
  bigbluebutton-html5/private/static/guest-wait/guest-wait.html
Labels: module: client, target: localization

#12219 feat(bbb-html5): localize guest-wait.html (part2)
  bigbluebutton-html5/private/static/guest-wait/guest-wait.html
Labels: module: client, target: localization

#12225 chore: Removed "dev" from 2.3 versioning in settings.yml
  bigbluebutton-html5/private/config/settings.yml
Labels: module: client
