Repository bigbluebutton/bigbluebutton, pull requests merged in 2021-12, with the labels that each got.

#13678 feat: Auto assign Breakouts (names and users) using previous rooms info or groups info
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutRoomUsersUpdateMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/domain/MeetingState2x.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
  bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala
  bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Group.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
  bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
  bigbluebutton-html5/client/collection-mirror-initializer.js
  bigbluebutton-html5/imports/api/breakouts-history/index.js
  bigbluebutton-html5/imports/api/breakouts-history/server/eventHandlers.js
  bigbluebutton-html5/imports/api/breakouts-history/server/handlers/breakoutRoomsList.js
  bigbluebutton-html5/imports/api/breakouts-history/server/index.js
  bigbluebutton-html5/imports/api/breakouts-history/server/publishers.js
  bigbluebutton-html5/imports/api/breakouts/server/eventHandlers.js
  bigbluebutton-html5/imports/api/breakouts/server/handlers/joinedUsersChanged.js
  bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
  bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/updateUserBreakoutRoom.js
  bigbluebutton-html5/imports/api/users-persistent-data/server/publishers.js
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
  bigbluebutton-html5/imports/ui/components/actions-bar/service.js
  bigbluebutton-html5/imports/ui/components/breakout-room/service.js
  bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/container.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx
  bigbluebutton-html5/public/locales/en.json
  bigbluebutton-html5/server/main.js
Labels: component: breakout rooms

#13697 Prevent unnecessary file copying in presentation recording processing
  record-and-playback/core/lib/recordandplayback/generators/events.rb
  record-and-playback/core/lib/recordandplayback/generators/video.rb
  record-and-playback/presentation/scripts/process/presentation.rb
Labels: module: recording

#13762 Update Nokogiri + Optimist
  record-and-playback/core/Gemfile
  record-and-playback/core/Gemfile.lock
  record-and-playback/core/scripts/archive/archive.rb
  record-and-playback/core/scripts/bbb-0.9-beta-recording-update
  record-and-playback/core/scripts/bbb-0.9-recording-size
  record-and-playback/core/scripts/bbb-1.1-meeting-tag
  record-and-playback/core/scripts/post_archive/post_archive.rb.example
  record-and-playback/core/scripts/post_process/post_process.rb.example
  record-and-playback/core/scripts/post_publish/post_publish.rb.example
  record-and-playback/core/scripts/post_publish/post_publish_recording_ready_callback.rb
  record-and-playback/core/scripts/sanity/sanity.rb
  record-and-playback/core/scripts/utils/captions.rb
  record-and-playback/notes/scripts/process/notes.rb
  record-and-playback/notes/scripts/publish/notes.rb
  record-and-playback/podcast/scripts/process/podcast.rb
  record-and-playback/podcast/scripts/publish/podcast.rb
  record-and-playback/presentation/scripts/process/presentation.rb
  record-and-playback/presentation/scripts/publish/presentation.rb
  record-and-playback/screenshare/scripts/process/screenshare.rb
  record-and-playback/screenshare/scripts/publish/screenshare.rb
Labels: module: recording

#13183 Update install-local.sh
  bbb-libreoffice/install-local.sh
Labels: cla: signed

#13918 Bug fix: support recordings with no fill attribute
  record-and-playback/presentation/scripts/publish/presentation.rb
Labels: module: recording

#13855 added drawImageProp function
  bigbluebutton-html5/imports/ui/services/virtual-background/index.js
Labels: cla: signed
