Repository bigbluebutton/bigbluebutton, pull requests merged in 2021-07, with the labels that each got.

#12704 Filter anonymous poll data for presenter, moderators and viewers
  bigbluebutton-html5/imports/api/polls/server/publishers.js
  bigbluebutton-html5/imports/ui/components/poll/component.jsx
  bigbluebutton-html5/imports/ui/components/poll/container.jsx
  bigbluebutton-html5/imports/ui/components/poll/service.js
Labels: component: polling

#12564 Adds possibility to give a name to breakout rooms
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/BreakoutModel.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutRoomCreatedMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutRoomsListMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/domain/BreakoutRoom2x.scala
  bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/BreakoutMsgs.scala
  bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/CreateBreakoutRoom.java
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.scss
  bigbluebutton-html5/imports/ui/components/actions-bar/service.js
  bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
  bigbluebutton-html5/imports/ui/components/breakout-room/styles.scss
  bigbluebutton-html5/public/locales/en.json
Labels: component: breakout rooms

#12495 Virtual background
  bigbluebutton-html5/imports/startup/server/index.js
  bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
  bigbluebutton-html5/imports/ui/components/video-preview/service.js
  bigbluebutton-html5/imports/ui/components/video-preview/styles.scss
  bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
  bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/styles.scss
  bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
  bigbluebutton-html5/imports/ui/components/video-provider/service.js
  bigbluebutton-html5/imports/ui/components/video-provider/stream-sorting.js
  bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
  bigbluebutton-html5/imports/ui/services/unread-messages/index.js
  bigbluebutton-html5/imports/ui/services/virtual-background/README.md
  bigbluebutton-html5/imports/ui/services/virtual-background/TimeWorker.js
  bigbluebutton-html5/imports/ui/services/virtual-background/index.js
  bigbluebutton-html5/imports/ui/services/virtual-background/service.js
  bigbluebutton-html5/imports/ui/services/virtual-background/tflite/tflite-simd.js
  bigbluebutton-html5/imports/ui/services/virtual-background/tflite/tflite-simd.wasm
  bigbluebutton-html5/imports/ui/services/virtual-background/tflite/tflite.js
  bigbluebutton-html5/imports/ui/services/virtual-background/tflite/tflite.wasm
  bigbluebutton-html5/imports/ui/services/webrtc-base/bbb-video-stream.js
  bigbluebutton-html5/package-lock.json
  bigbluebutton-html5/package.json
  bigbluebutton-html5/private/config/settings.yml
  bigbluebutton-html5/private/wasm/tflite-simd.wasm
  bigbluebutton-html5/private/wasm/tflite.wasm
  bigbluebutton-html5/public/locales/en.json
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/architecture.jpg
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/board.jpg
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/brickwall.jpg
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/coffeeshop.jpg
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/home.jpg
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/thumbnails/blur.jpg
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/thumbnails/board.jpg
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/thumbnails/coffeeshop.jpg
  bigbluebutton-html5/public/resources/images/virtual-backgrounds/thumbnails/home.jpg
  bigbluebutton-html5/public/resources/tfmodels/segm_full_v679.tflite
  bigbluebutton-html5/public/resources/tfmodels/segm_lite_v681.tflite
Labels: cla: signed

#12854 fix: Announce new private chat messages in screenreader
  bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/chat-unread-messages/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/component.jsx
  bigbluebutton-html5/public/locales/en.json
Labels: target: accessibilty

#12878 chore: Pulled HTML5 locales in 2.4; adjusted transifex.sh
  bigbluebutton-html5/public/locales/af.json
  bigbluebutton-html5/public/locales/ar.json
  bigbluebutton-html5/public/locales/az.json
  bigbluebutton-html5/public/locales/bg_BG.json
  bigbluebutton-html5/public/locales/ca.json
  bigbluebutton-html5/public/locales/cs_CZ.json
  bigbluebutton-html5/public/locales/de.json
  bigbluebutton-html5/public/locales/dv.json
  bigbluebutton-html5/public/locales/eo.json
  bigbluebutton-html5/public/locales/es_MX.json
  bigbluebutton-html5/public/locales/et.json
  bigbluebutton-html5/public/locales/eu.json
  bigbluebutton-html5/public/locales/fa_IR.json
  bigbluebutton-html5/public/locales/fi.json
  bigbluebutton-html5/public/locales/fr.json
  bigbluebutton-html5/public/locales/gl.json
  bigbluebutton-html5/public/locales/he.json
  bigbluebutton-html5/public/locales/hi_IN.json
  bigbluebutton-html5/public/locales/hr.json
  bigbluebutton-html5/public/locales/hu_HU.json
  bigbluebutton-html5/public/locales/id.json
  bigbluebutton-html5/public/locales/it_IT.json
  bigbluebutton-html5/public/locales/ja.json
  bigbluebutton-html5/public/locales/ka.json
  bigbluebutton-html5/public/locales/kn.json
  bigbluebutton-html5/public/locales/ko_KR.json
  bigbluebutton-html5/public/locales/lv.json
  bigbluebutton-html5/public/locales/nb_NO.json
  bigbluebutton-html5/public/locales/nl.json
  bigbluebutton-html5/public/locales/oc.json
  bigbluebutton-html5/public/locales/pl_PL.json
  bigbluebutton-html5/public/locales/pt.json
  bigbluebutton-html5/public/locales/pt_BR.json
  bigbluebutton-html5/public/locales/ro_RO.json
  bigbluebutton-html5/public/locales/sk_SK.json
  bigbluebutton-html5/public/locales/sv_SE.json
  bigbluebutton-html5/public/locales/te.json
  bigbluebutton-html5/public/locales/th.json
  bigbluebutton-html5/public/locales/tr.json
  bigbluebutton-html5/public/locales/tr_TR.json
  bigbluebutton-html5/public/locales/vi_VN.json
  bigbluebutton-html5/public/locales/zh_CN.json
  bigbluebutton-html5/transifex.sh
Labels: target: localization
