Repository bigbluebutton/bigbluebutton, pull requests merged in 2021-05, with the labels that each got.

#12266 fix: Add margin between record button and time
  bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss
Labels: module: client

#12275 fix: bug in playAudioAlert method
  bigbluebutton-html5/imports/ui/components/activity-check/component.jsx
Labels: module: client

#12273 fix: prevent an extra audio channel to be created when skipCheckOnJoin is true
  bigbluebutton-html5/imports/ui/components/audio/audio-modal/service.js
Labels: module: audio

#12264 feat(accessibility): Improve keyboard Access For Breakout Room Assignment
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
Labels: module: client, target: accessibilty

#12317 Fit conversion error message in toast notification
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss
Labels: component: presentation, module: client

#12322 Add scroll to poll question container
  bigbluebutton-html5/imports/ui/components/polling/styles.scss
Labels: component: polling

#12325 chore: Updated lint-staged from 8.1.3 to 11.0.0
  bigbluebutton-html5/package-lock.json
  bigbluebutton-html5/package.json
Labels: module: client

#12321 fix: chat jumps to top when opened/closed
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Labels: component: chat, module: client

#12354 fix: handle new message auto-scroll in chat
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Labels: component: chat

#12404 feat: add setting to enable/disable raise hand action button
  bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
  bigbluebutton-html5/private/config/settings.yml
Labels: module: client

#12405 fix(chat): auto scroll to bottom for new users
  bigbluebutton-html5/imports/ui/components/chat/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
  bigbluebutton-html5/imports/ui/components/chat/time-window-list/container.jsx
Labels: component: chat

#12423 fix: handle additional cases for locales
  bigbluebutton-html5/imports/startup/server/index.js
Labels: module: client, target: localization

#12428 feat: localization support for guest wait page
  bigbluebutton-html5/private/static/guest-wait/guest-wait.html
  bigbluebutton-html5/public/locales/en.json
Labels: module: client, target: localization

#12372 Show the status of multiple nodejs workers and kurento media servers in bbb-conf status
  bigbluebutton-config/bin/bbb-conf
Labels: cla: signed

#12173 Mobile/Tablet devices automated tests for mobile/tablet on ios/android devices
  bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
  bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
  bigbluebutton-html5/tests/puppeteer/audio.obj.js
  bigbluebutton-html5/tests/puppeteer/audio/elements.js
  bigbluebutton-html5/tests/puppeteer/breakout/create.js
  bigbluebutton-html5/tests/puppeteer/core/devices.js
  bigbluebutton-html5/tests/puppeteer/core/elements.js
  bigbluebutton-html5/tests/puppeteer/core/page.js
  bigbluebutton-html5/tests/puppeteer/core/profiles.js
  bigbluebutton-html5/tests/puppeteer/customparameters.obj.js
  bigbluebutton-html5/tests/puppeteer/notifications/notifications.js
  bigbluebutton-html5/tests/puppeteer/screenshare.obj.js
  bigbluebutton-html5/tests/puppeteer/screenshare/screenshare.js
  bigbluebutton-html5/tests/puppeteer/screenshare/util.js
  bigbluebutton-html5/tests/puppeteer/user.obj.js
  bigbluebutton-html5/tests/puppeteer/user/elements.js
  bigbluebutton-html5/tests/puppeteer/user/multiusers.js
  bigbluebutton-html5/tests/puppeteer/webcam.obj.js
  bigbluebutton-html5/tests/puppeteer/webcamlayout.obj.js
Labels: type: test

#12450 refactor: Isolate recording apis into RecordingController
  bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/UrlMappings.groovy
  bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
  bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/RecordingController.groovy
Labels: module: core

#12484 fix(bbb-conf):Only show status for multi kurento if that is configured
  bigbluebutton-config/bin/bbb-conf
Labels: deploy: configuration
