Repository bigbluebutton/bigbluebutton, pull requests merged in 2022-02, with the labels that each got.

#14254 refactor(locale): adjust playback ids
  bigbluebutton-html5/public/locales/en.json
Labels: deploy: configuration, target: localization, type: refactor

#14274 build(etherpad): add soffice path
  build/packages-template/bbb-etherpad/settings.json
Labels: type: enhancement, deploy: configuration, component: shared notes, component: closed captions

#14345 build(bbb-pads): bump v1.0.2
  bbb-pads.placeholder.sh
Labels: type: defect, deploy: packaging, target: robustness, component: shared notes, component: closed captions

#14264 Created endpoint to insert file into presentation.
  bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/InsertDocument.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/service/ValidationService.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/util/ResponseBuilder.java
  bbb-common-web/src/test/resources/insert-document.ftlx
  bigbluebutton-html5/imports/api/presentations/server/handlers/presentationAdded.js
  bigbluebutton-html5/imports/api/presentations/server/modifiers/addPresentation.js
  bigbluebutton-html5/imports/api/presentations/server/modifiers/setCurrentPresentation.js
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
  bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
  bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/insert-document.ftlx
Labels: module: api

#14225 refactor(recording): Refactored record-and-playback's deploy script to work properly
  record-and-playback/deploy.sh
Labels: module: recording
