Repository bigbluebutton/bigbluebutton, pull requests merged in 2022-05, with the labels that each got.

#14928 record-and-playback: Don't seek past end of video input
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording, type: bug

#14929 record-and-playback: Don't seek past end of video input (BBB 2.4)
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording, type: bug

#15053 fix: set target to jvm-1.11 in akka-bbb-fsesl
  akka-bbb-fsesl/build.sbt
Labels: module: core

#15106 feat(webcam) camera avatar polishment
  bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
  bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js
  bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-avatar/component.jsx
  bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/styles.js
Labels: module: client, component: webcam
