Repository bigbluebutton/bigbluebutton, pull requests merged in 2022-12, with the labels that each got.

#16265 fix: Update Control Labels In Settings
  bigbluebutton-html5/imports/ui/components/common/locales-dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/settings/component.jsx
  bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
  bigbluebutton-html5/imports/ui/components/settings/submenus/data-saving/component.jsx
  bigbluebutton-html5/imports/ui/components/settings/submenus/notification/component.jsx
Labels: target: accessibilty

#16263 fix: Remove Aria Live From Captions
  bigbluebutton-html5/imports/ui/components/captions/live/component.jsx
Labels: target: accessibilty

#15767 ci: add minimum GitHub token permissions for workflow
  .github/workflows/check-merge-conflict.yml
Labels: cla: signed, cla: required

#15727 fix(audio conf): Revert jitterbuffer values & increase them
  bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_conference.xml
  bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml
Labels: cla: signed
