Repository bigbluebutton/bigbluebutton, pull requests merged in 2022-01, with the labels that each got.

#14105 Fix: Improve typing input behavior of poll option text fields
  bigbluebutton-html5/imports/ui/components/poll/component.jsx
Labels: component: polling

#14019 fix(recording): not processed screenshare
  record-and-playback/screenshare/scripts/screenshare.yml
Labels: module: recording, cla: signed

#14133 fix(recording): not processed screenshare fix issue #13356
  record-and-playback/screenshare/scripts/screenshare.yml
Labels: module: recording

#9837 fix(recording): Generate thumbnails from uploaded file
  record-and-playback/core/lib/recordandplayback/generators/presentation.rb
Labels: module: recording, cla: signed

#9570 fix(recording): Generate thumbnails from uploaded file (backport)
  record-and-playback/core/lib/recordandplayback/generators/presentation.rb
Labels: module: recording, cla: signed

#14170 fix(recording): fix publish crash when poll has no options/answers
  record-and-playback/presentation/scripts/publish/presentation.rb
Labels: module: recording, component: polling

#14184 Add Polite Presentation Slide Change Announcement (Screen Reader)
  bigbluebutton-html5/client/main.html
  bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/component.jsx
  bigbluebutton-html5/imports/utils/dom-utils.js
  bigbluebutton-html5/public/locales/en.json
Labels: target: accessibilty

#14067 Add private guest lobby messages
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/GuestsApp.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/GuestsWaiting.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/guests/SetPrivateGuestLobbyMessageCmdMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala
  bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GuestsMsgs.scala
  bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/PrivateGuestLobbyMessageChanged.java
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/bus/ReceivedJsonMsgHdlrActor.scala
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
  bigbluebutton-html5/imports/api/guest-users/server/eventHandlers.js
  bigbluebutton-html5/imports/api/guest-users/server/handlers/guestsWaitingForApproval.js
  bigbluebutton-html5/imports/api/guest-users/server/handlers/privateGuestLobbyMessageChanged.js
  bigbluebutton-html5/imports/api/guest-users/server/methods.js
  bigbluebutton-html5/imports/api/guest-users/server/methods/setPrivateGuestLobbyMessage.js
  bigbluebutton-html5/imports/api/guest-users/server/modifiers/setPrivateGuestLobbyMessage.js
  bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
  bigbluebutton-html5/imports/ui/components/waiting-users/container.jsx
  bigbluebutton-html5/imports/ui/components/waiting-users/service.js
  bigbluebutton-html5/imports/ui/components/waiting-users/styles.js
  bigbluebutton-html5/public/locales/en.json
  bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Labels: status: accepted, type: enhancement, module: web, module: client, cla: signed

#14063 Add position in waiting queue for guest users
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/GuestsApp.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/guests/UpdatePositionInWaitingQueueReqMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala
  bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GuestsMsgs.scala
  bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/PositionInWaitingQueueUpdated.java
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/bus/ReceivedJsonMsgHdlrActor.scala
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
  bigbluebutton-html5/imports/api/guest-users/server/handlers/guestsWaitingForApproval.js
  bigbluebutton-html5/imports/api/guest-users/server/methods/updatePositionInWaitingQueue.js
  bigbluebutton-html5/imports/api/guest-users/server/modifiers/removeGuest.js
  bigbluebutton-html5/imports/api/guest-users/server/modifiers/setGuestStatus.js
  bigbluebutton-html5/private/static/guest-wait/guest-wait.html
  bigbluebutton-html5/public/locales/en.json
  bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Labels: cla: signed

#14022 bbb-record: refactoring, more config checks, list-workflows option
  bigbluebutton-config/bin/bbb-record
Labels: module: recording

#11405 style: Use different colors for allow and deny buttons in waiting room
  bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
Labels: module: client
