Repository bigbluebutton/bigbluebutton, pull requests merged in 2023-04, with the labels that each got.

#17398 docs: make 2.6 the default version in docs
  docs/docusaurus.config.js
Labels: target: documentation

#17439 recording-and-playback/presentation: Fix hiding tldraw cursors
  record-and-playback/presentation/scripts/publish/presentation.rb
Labels: module: recording

#17463 docs: Fix for tables broken references
  docs/docs/development/api.md
  docs/src/components/APITableComponent/index.tsx
  docs/src/components/APITableComponent/styles.module.css
  docs/src/data/create.tsx
  docs/src/data/deleteRecordings.tsx
  docs/src/data/end.tsx
  docs/src/data/getMeetingInfo.tsx
  docs/src/data/getRecordingTextTracks.tsx
  docs/src/data/getRecordings.tsx
  docs/src/data/insertDocument.tsx
  docs/src/data/isMeetingRunning.tsx
  docs/src/data/join.tsx
  docs/src/data/publishRecordings.tsx
  docs/src/data/putRecordingTextTrack.tsx
  docs/src/data/updateRecordings.tsx
Labels: target: documentation

#16115 fix: Handle External Video Links On Multi Lines In Smart Slides
  bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/smart-video-share/component.jsx
Labels: priority: low

#17349 docs: Update url for GL migration path
  docs/docs/greenlight/v3/migration.md
Labels: cla: signed

#17433 docs: Issue#17103-Updated TURN server document for BBB 2.6
  bigbluebutton-html5/private/config/settings.yml
  docs/docs/administration/turn-server.md
Labels: cla: signed

#17527 bbb-presentation-video: update to 4.0.2
  bbb-presentation-video.placeholder.sh
Labels: module: recording

#17519 docs: Update breakout capture API reference
  docs/docs/data/create.tsx
  docs/docs/development/dev-guide.md
Labels: target: documentation

#17550 docs: include info on TURN being set up by default in 2.6+
  docs/docs/administration/install.md
  docs/docs/new-features.md
Labels: target: documentation

#17552 docs: Handle paths /2.6/new-features, /dev/ and /admin/
  docs/docusaurus.config.js
Labels: target: documentation

#17560 docs: Document join parameter `errorRedirectUrl`
  docs/docs/data/join.tsx
  docs/docs/development/api.md
Labels: target: documentation

#17432 Docs: Added `Relative URL ... Setup` section to Greenlight 3 install chapter.
  docs/docs/greenlight/v3/install.md
Labels: target: documentation

#17713 docs: Correcting the virtual background images upload path
  docs/docs/administration/customize.md
Labels: cla: signed

#17770 build: bbb-graphql-server copy metadata and bbb_schema.sql
  bbb-graphql-server/hasura-config.env
  build/packages-template/bbb-graphql-server/after-install.sh
  build/packages-template/bbb-graphql-server/build.sh
Labels: status: conflict
