Repository bigbluebutton/bigbluebutton, pull requests merged in 2023-03, with the labels that each got.

#16540 test: initial layout management tests
  bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx
  bigbluebutton-tests/playwright/core/elements.js
  bigbluebutton-tests/playwright/layouts/focusOnPresentation.js
  bigbluebutton-tests/playwright/layouts/focusOnVideo.js
  bigbluebutton-tests/playwright/layouts/layouts.spec.js
  bigbluebutton-tests/playwright/layouts/layouts.spec.js-snapshots/moderator1-focus-on-presentation-Chromium-linux.png
  bigbluebutton-tests/playwright/layouts/layouts.spec.js-snapshots/moderator1-focus-on-video-Chromium-linux.png
  bigbluebutton-tests/playwright/layouts/layouts.spec.js-snapshots/moderator2-focus-on-presentation-Chromium-linux.png
  bigbluebutton-tests/playwright/layouts/layouts.spec.js-snapshots/moderator2-focus-on-video-Chromium-linux.png
Labels: priority: normal

#16925 build(bbb-presentation-video): Update to 4.0.0-rc.1
  .gitignore
  bbb-presentation-video.placeholder.sh
Labels: module: recording

#16754 fix: Banned user sees message upon return attempt (before - only blue screen)
  bigbluebutton-html5/imports/startup/client/base.jsx
  bigbluebutton-html5/imports/ui/services/auth/index.js
Labels: priority: high

#16952 fix: avoid wb crash when switching presentation
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Labels: priority: high

#16958 fix: whiteboard crash with new presentation
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Labels: priority: high

#16970 docs: sync up 2.6 docs
  .github/workflows/automated-tests.yml
  docs/docs/new-features.md
Labels: target: documentation

#17061 docs: Include missing API docs for v2.6.x release
  docs/docs/development/api.md
Labels: cla: signed

#17115 docs: marking 2.6.0 as stable
  docs/docs/administration/install.md
  docs/docs/new-features.md
  docs/docs/support/road-map.md
  docs/src/components/HomepageFeatures/index.tsx
Labels: target: documentation

#17152 docs: Link to the current end user support pages
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/pages/index.tsx
Labels: target: documentation

#17112 recording: Fix video processing OOM, Broken pipe errors
  record-and-playback/core/lib/recordandplayback/edl/video.rb
  record-and-playback/core/lib/recordandplayback/generators/events.rb
Labels: module: recording

#17116 recording: Fix video processing OOM, Broken pipe errors (2.5 backport)
  record-and-playback/core/lib/recordandplayback/edl/video.rb
  record-and-playback/core/lib/recordandplayback/generators/events.rb
Labels: module: recording

#17201 recording/video: Fix typo in area layout
  record-and-playback/video/scripts/video.yml
Labels: module: recording

#16989 fix(access): Presentation Interference With Keyboard Access in Breakout Management
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
  bigbluebutton-html5/imports/ui/components/presentation/component.jsx
Labels: target: accessibilty

#17324 docs: Forward from old docs API link
  docs/docusaurus.config.js
Labels: target: documentation

#17329 recording: Increase quality of libx264 intermediate files
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording

#17242 fix(bbb-presentation-video): Update to 4.0.0
  bbb-presentation-video.placeholder.sh
Labels: module: recording

#17347 bbb-presentation-video: Update to 4.0.1
  bbb-presentation-video.placeholder.sh
Labels: module: recording

#17362 fix(recording): crash on redisrecorderactor when poll is published
  akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
Labels: priority: high

#17379 recording: Fix video processing incompatibility with Ruby 2.7
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording

#17385 test: update instructions to only test specific browser
  bigbluebutton-tests/playwright/README.md
Labels: type: test

#17389 docs: fixed reseting to default version in bbb documentation
  docs/docusaurus.config.js
Labels: target: documentation
