Repository bigbluebutton/bigbluebutton, pull requests merged in 2023-02, with the labels that each got.

#16621 fix: Poll is breaking when trying to add more than 5 answer items
  bigbluebutton-html5/imports/ui/components/poll/component.jsx
  bigbluebutton-html5/imports/ui/components/poll/service.js
Labels: priority: high

#16655 fix(docs): Make index page behave in dark mode and fix spacing
  docs/src/css/custom.css
Labels: target: documentation

#15269 feat(bbb-config): Override of cronjob variables
  bigbluebutton-config/cron.daily/bigbluebutton
Labels: priority: normal

#16698 recording: video format updates & fixes
  record-and-playback/core/lib/recordandplayback/generators/events.rb
  record-and-playback/video/scripts/process/video.rb
  record-and-playback/video/scripts/video.yml
Labels: module: recording

#16721 fix: Sticky notes are giant on portrait view slides
  bigbluebutton-html5/imports/api/slides/server/helpers.js
Labels: priority: high

#15999 Fix: dismiss toast on unmount
  bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx
  bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
Labels: priority: normal

#15728 feat: Emoji Status Control in Raise Hand Button
  bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/container.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/styles.js
Labels: cla: signed

#16740 recording: Enforce minimum length of video segments, etc.
  record-and-playback/core/lib/recordandplayback/edl/video.rb
  record-and-playback/core/lib/recordandplayback/generators/events.rb
  record-and-playback/core/test/recordandplayback/edl/test_video.rb
  record-and-playback/core/test/recordandplayback/generators/test_events.rb
Labels: module: recording

#16686 (docs/ci): Docs deployment
  .github/workflows/deploy-docs.yml
  docs/.gitignore
  docs/README.md
  docs/build.sh
  docs/docusaurus.config.js
Labels: target: documentation

#16741 recording: Enforce minimum length of video segments, etc. (2.5 backport)
  record-and-playback/core/lib/recordandplayback/edl/video.rb
  record-and-playback/core/lib/recordandplayback/generators/events.rb
  record-and-playback/core/test/recordandplayback/edl/test_video.rb
  record-and-playback/core/test/recordandplayback/generators/test_events.rb
Labels: module: recording

#16774 fix(recording): Recording stability & A/V sync fixes
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording

#16752 fix(access): Move Focus To Polling Option When Presented
  bigbluebutton-html5/imports/ui/components/polling/component.jsx
  bigbluebutton-html5/imports/ui/components/polling/styles.js
Labels: target: accessibilty

#16737 fix(access): Darken Color Contrast For Non Compliant Elements
  bbb-learning-dashboard/src/App.js
  bbb-learning-dashboard/src/components/UsersTable.jsx
  bbb-learning-dashboard/src/index.css
Labels: target: accessibilty

#16738 fix(access): Add Context To Time Values in Learning Dashboard User Details
  bbb-learning-dashboard/src/components/UserDetails/component.jsx
Labels: target: accessibilty

#16780 (docs/ci): Use actions publishing for pages
  .github/workflows/deploy-docs.yml
Labels: target: documentation

#16784 (docs/ci): Build docs on workflow changes
  .github/workflows/deploy-docs.yml
  docs/.gitignore
  docs/README.md
  docs/build.sh
  docs/docusaurus.config.js
Labels: target: documentation
