Repository bigbluebutton/bigbluebutton, pull requests merged in 2023-01, with the labels that each got.

#16387 fix: Add Active Status to Presentation Menu Item for SR
  bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
  bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
Labels: target: accessibilty

#16409 Recording: move tpad ffmpeg filter before fps
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording

#16410 Recording: move tpad ffmpeg filter before fps (2.5 backport)
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording

#16538 refactor (html5): Rename breakoutroom configs
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
  bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx
  bigbluebutton-html5/private/config/settings.yml
Labels: priority: normal

#15691 fix/refactor: Rtt routine not alerting when user lose connection with server
  bigbluebutton-html5/imports/api/connection-status/server/methods/addConnectionStatus.js
  bigbluebutton-html5/imports/api/connection-status/server/modifiers/updateConnectionStatus.js
  bigbluebutton-html5/imports/ui/components/connection-status/button/component.jsx
  bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
  bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.js
  bigbluebutton-html5/imports/ui/components/connection-status/service.js
  bigbluebutton-html5/public/locales/en.json
Labels: priority: high

#16545 fix: setPresentationIsOpen is undefined
  bigbluebutton-html5/imports/ui/components/presentation/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/container.jsx
Labels: priority: high

#16543 fix(whiteboard): prevent crashes when grouped shapes are removed
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Labels: priority: high

#16525 fix: check for shape before shape.isLocked
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Labels: priority: high

#16107 fix(audio): add delay for loopback test
  bigbluebutton-html5/imports/ui/components/audio/local-echo/service.js
  bigbluebutton-html5/private/config/settings.yml
Labels: priority: normal

#16506 test: Increase/Decrease font-size
  bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
  bigbluebutton-tests/playwright/core/elements.js
  bigbluebutton-tests/playwright/core/page.js
  bigbluebutton-tests/playwright/options/options.js
  bigbluebutton-tests/playwright/options/options.spec.js
Labels: priority: normal

#16517 feat: Video recording format processing scripts
  build/packages-template/bbb-playback-video/after-install.sh
  build/packages-template/bbb-playback-video/build.sh
  build/packages-template/bbb-playback-video/opts-focal.sh
  record-and-playback/video/playback/video/css/normalize.css
  record-and-playback/video/playback/video/css/video.css
  record-and-playback/video/playback/video/index.html.erb
  record-and-playback/video/playback/video/js/popcorn-complete.min.js
  record-and-playback/video/playback/video/js/popcorn.chattimeline.js
  record-and-playback/video/playback/video/js/video.js
  record-and-playback/video/playback/video/video-js/font/VideoJS.eot
  record-and-playback/video/playback/video/video-js/font/VideoJS.svg
  record-and-playback/video/playback/video/video-js/font/VideoJS.ttf
  record-and-playback/video/playback/video/video-js/font/VideoJS.woff
  record-and-playback/video/playback/video/video-js/lang/ar.js
  record-and-playback/video/playback/video/video-js/lang/ba.js
  record-and-playback/video/playback/video/video-js/lang/bg.js
  record-and-playback/video/playback/video/video-js/lang/ca.js
  record-and-playback/video/playback/video/video-js/lang/cs.js
  record-and-playback/video/playback/video/video-js/lang/da.js
  record-and-playback/video/playback/video/video-js/lang/de.js
  record-and-playback/video/playback/video/video-js/lang/el.js
  record-and-playback/video/playback/video/video-js/lang/en.js
  record-and-playback/video/playback/video/video-js/lang/es.js
  record-and-playback/video/playback/video/video-js/lang/fa.js
  record-and-playback/video/playback/video/video-js/lang/fi.js
  record-and-playback/video/playback/video/video-js/lang/fr.js
  record-and-playback/video/playback/video/video-js/lang/hr.js
  record-and-playback/video/playback/video/video-js/lang/hu.js
  record-and-playback/video/playback/video/video-js/lang/it.js
  record-and-playback/video/playback/video/video-js/lang/ja.js
  record-and-playback/video/playback/video/video-js/lang/ko.js
  record-and-playback/video/playback/video/video-js/lang/nb.js
  record-and-playback/video/playback/video/video-js/lang/nl.js
  record-and-playback/video/playback/video/video-js/lang/nn.js
  record-and-playback/video/playback/video/video-js/lang/pl.js
  record-and-playback/video/playback/video/video-js/lang/pt-BR.js
  record-and-playback/video/playback/video/video-js/lang/ru.js
  record-and-playback/video/playback/video/video-js/lang/sr.js
  record-and-playback/video/playback/video/video-js/lang/sv.js
  record-and-playback/video/playback/video/video-js/lang/tr.js
  record-and-playback/video/playback/video/video-js/lang/uk.js
  record-and-playback/video/playback/video/video-js/lang/vi.js
  record-and-playback/video/playback/video/video-js/lang/zh-CN.js
  record-and-playback/video/playback/video/video-js/lang/zh-TW.js
  record-and-playback/video/playback/video/video-js/video-js.min.css
  record-and-playback/video/playback/video/video-js/video.min.js
  record-and-playback/video/scripts/playback-video.nginx
  record-and-playback/video/scripts/process/video.rb
  record-and-playback/video/scripts/publish/video.rb
  record-and-playback/video/scripts/video.yml
Labels: priority: high

#16539 fix: Update Tldraw Toolbar Placement
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Labels: priority: low

#16564 fix(whiteboard): Incorrect pen position after column resize
  bigbluebutton-html5/imports/ui/components/presentation/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Labels: priority: high

#16557 Move Visible Accessibility Warning Note To Aria Tag / Tooltip
  bigbluebutton-html5/imports/ui/components/chat/service.js
  bigbluebutton-html5/public/locales/en.json
Labels: priority: low

#16561 fix(access): Make Timeline Actions Visible to Screen Reader
  bbb-learning-dashboard/src/components/StatusTable.jsx
Labels: priority: normal, target: accessibilty

#16584 fix(whiteboard): Prevent infinite zoom levels
  bigbluebutton-html5/imports/api/slides/server/methods/zoomSlide.js
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Labels: component: whiteboard

#16582 fix(whiteboard): improve invalid shape filter
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Labels: priority: high

#16585 fix: modal initialisation
  bigbluebutton-html5/imports/ui/components/common/modal/service.js
Labels: priority: high

#16583 refactor: Detect mime-type flow improvements
  bbb-common-web/src/main/java/org/bigbluebutton/presentation/SupportedFileTypes.java
Labels: priority: normal
