Repository bigbluebutton/bigbluebutton, pull requests merged in 2024-11, with the labels that each got.

#21723 fix(whiteboard): Improve tldraw camera and zoom stability
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
  bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Labels: priority: high

#21204 feat: Allow per user logout url
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala
  akka-bbb-apps/src/test/scala/org/bigbluebutton/core2/testdata/TestDataGen.scala
  bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala
  bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/domain/RegisteredUser.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/RegisterUser.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/pub/IPublisherService.java
  bbb-common-web/src/main/java/org/bigbluebutton/api/service/ValidationService.java
  bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/MeetingsManagerActor.scala
  bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/ToAkkaAppsSendersTrait.scala
  bbb-graphql-server/bbb_schema.sql
  bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
  bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
  bigbluebutton-html5/imports/ui/components/meeting-ended/queries.ts
  bigbluebutton-html5/package-lock.json
  bigbluebutton-html5/package.json
  bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
  docs/docs/data/join.tsx
Labels: cla: signed

#21778 chore: Enable by default chat edit, delete, reply, reactions
  bigbluebutton-html5/private/config/settings.yml
Labels: status: conflict
