Repository bigbluebutton/bigbluebutton, pull requests merged in 2025-02, with the labels that each got.

#22150 Accessibility: improve userlists
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx
  bigbluebutton-html5/imports/ui/components/waiting-users/waiting-users-graphql/guest-items/guestPendingUser.tsx
  bigbluebutton-html5/imports/ui/components/waiting-users/waiting-users-graphql/guest-items/guestUserItem.tsx
Labels: target: accessibilty

#22147 Accessibility: improve screenreader navigation
  bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
  bigbluebutton-html5/imports/ui/components/presentation/component.jsx
  bigbluebutton-html5/imports/ui/components/webcam/component.tsx
  bigbluebutton-html5/public/locales/en.json
Labels: target: accessibilty

#22207 fix(whiteboard): Remove duplicate zoom propagation
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Labels: priority: high

#22117 fix: Add access key for leave meeting dropdown menu
  bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
  bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx
  bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/container.jsx
  bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
  bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
  bigbluebutton-html5/private/config/settings.yml
  bigbluebutton-html5/public/locales/en.json
Labels: target: accessibilty

#22138 fix(chat): Keyboard navigation + message accessibility
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/reaction-item/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/styles.ts
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts
  bigbluebutton-html5/imports/ui/core/enums/chat.ts
Labels: target: accessibilty

#21885 impr(bbb-record): Clarify recording status output
  bigbluebutton-config/bin/bbb-record
Labels: cla: signed
