Repository bigbluebutton/bigbluebutton, pull requests merged in 2025-09, with the labels that each got.

#23828 fix: wrong zoom position on slide change
  bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
  bigbluebutton-tests/playwright/presentation/presentation.spec.js
Labels: priority: high

#23902 recording: Fix flickering with overlapping video areas
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording

#23965 Fix #23964: avoid printing on the standard output in cron jobs
  bigbluebutton-config/cron.daily/bigbluebutton
Labels: cla: signed
