Repository bigbluebutton/bigbluebutton, pull requests merged in 2025-03, with the labels that each got.

#22453 docs: Adjust yq commands to yq version 4.16.2
  docs/docs/administration/customize.md
Labels: target: documentation

#22454 docs: update the portion about reducing webcam bandwidth
  docs/docs/administration/customize.md
Labels: target: documentation

#22151 fix(chat) Improve accessibility
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/component.tsx
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx
Labels: priority: high, target: accessibilty

#22481 Accessibility improvements
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/component.tsx
  bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
  bigbluebutton-html5/imports/ui/components/notes/component.tsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
  bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-list-content/user-notes/component.tsx
  bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.tsx
Labels: priority: high, target: accessibilty

#22655 docs: Include allowOverrideClientSettingsOnCreateCall mention in clientSettingsOverride
  docs/docs/development/api.md
Labels: target: documentation

#22679 docs: Adjust client title docs
  docs/docs/administration/customize.md
Labels: target: documentation

#22696 feat(html5): add control over default setting of breakout recordings
  bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
  bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
  bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
  bigbluebutton-html5/private/config/settings.yml
Labels: cla: signed

#22761 fix: client crash in breakout room mgmt panel
  bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/room-managment-state/component.tsx
Labels: component: breakout rooms

#22703 Speed up compositing of video in recording processing
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording

#22802 Fix(html5): Users being moved to room zero on running meetings causes a crash
  bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
Labels: component: breakout rooms
