Repository bigbluebutton/bigbluebutton, pull requests merged in 2025-04, with the labels that each got.

#22953 fix(html5): Chat auto scrolling glitch
  bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
Labels: priority: high

#23010 recording: check for videos with no decodable frames
  record-and-playback/core/lib/recordandplayback/edl/video.rb
Labels: module: recording, ruby

#23017 fix(html5/external-video): Make the player respect timestamp from URL
  akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ExternalVideoDAO.scala
  bigbluebutton-html5/imports/ui/Types/meeting.ts
  bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
Labels: component: external video
